name: Publish to PyPI

on:
  release:
    branches:
      - master
    types:
      - published

jobs:
  build-and-publish:
    name: Build and publish pySnowRadar to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup build env (Python 3.7)
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install wheel to build env
      run: |
        python -m pip install wheel --user
    - name: Build the source dist and wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}